// a função gets é implementada dentro do sistema para ler as entradas(inputs) dos dados e a função print para imprimir a saída (output) de dados e já pula uma linha ("\n")
// Abaixo segue um exemplo de código que você pode ou não utilizar

let Twitter ="RT @TheEllenShow: If only Bradley's arm was longer. Best photo ever. #oscars pic.twitter.com/C9U5NOtGap";

//TODO: Complete os espaços em branco com uma possível solução para o desafio

var resultado = (Twitter.length <= 140) ? "TWEET" : "MUTE"
print(resultado);