// a função gets é implementada dentro do sistema para ler as entradas(inputs) dos dados e a função print para imprimir a saída (output) de dados e já pula uma linha ("\n")
// Abaixo segue um exemplo de código que você pode ou não utilizar

var a = parseFloat(10.0);
var b = parseFloat(10.0);

//TODO: Complete os espaços em branco com uma possível solução para o desafio

var media = ((   a  * 3.5) + (    b  * 7.5))/  (11)     ;

media = media.toFixed(5)
console.log("MEDIA = " + media);